<?php
declare(strict_types=1);

namespace App\Test\TestCase\Service;

use App\Service\GmailService;
use Cake\TestSuite\TestCase;

/**
 * Mock Gmail header object for testing
 */
class MockGmailHeader
{
    private string $name;
    private string $value;

    /**
     * Constructor
     *
     * @param string $name Header name
     * @param string $value Header value
     */
    public function __construct(string $name, string $value)
    {
        $this->name = $name;
        $this->value = $value;
    }

    /**
     * Get header name
     *
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Get header value
     *
     * @return string
     */
    public function getValue(): string
    {
        return $this->value;
    }
}

/**
 * App\Service\GmailService Test Case
 */
class GmailServiceTest extends TestCase
{
    /**
     * Test subject
     *
     * @var \App\Service\GmailService
     */
    protected $GmailService;

    /**
     * setUp method
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp();
        // Create service without config (we're testing methods that don't need Gmail API)
        $this->GmailService = new GmailService([]);
    }

    /**
     * tearDown method
     *
     * @return void
     */
    protected function tearDown(): void
    {
        unset($this->GmailService);
        parent::tearDown();
    }

    /**
     * Helper to create mock Gmail headers
     *
     * @param array $headerData Associative array of header name => value
     * @return array Array of MockGmailHeader objects
     */
    private function createHeaders(array $headerData): array
    {
        $headers = [];
        foreach ($headerData as $name => $value) {
            $headers[] = new MockGmailHeader($name, $value);
        }
        return $headers;
    }

    /**
     * Test isAutoReply detects Auto-Submitted: auto-replied
     *
     * @return void
     */
    public function testIsAutoReplyDetectsAutoSubmittedAutoReplied(): void
    {
        $headers = $this->createHeaders([
            'From' => 'user@example.com',
            'Auto-Submitted' => 'auto-replied',
            'Subject' => 'Out of Office',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects Auto-Submitted: auto-generated
     *
     * @return void
     */
    public function testIsAutoReplyDetectsAutoSubmittedAutoGenerated(): void
    {
        $headers = $this->createHeaders([
            'From' => 'system@example.com',
            'Auto-Submitted' => 'auto-generated',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects X-Autoreply: yes
     *
     * @return void
     */
    public function testIsAutoReplyDetectsXAutoreplyYes(): void
    {
        $headers = $this->createHeaders([
            'From' => 'user@example.com',
            'X-Autoreply' => 'yes',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects X-Autorespond: yes
     *
     * @return void
     */
    public function testIsAutoReplyDetectsXAutorespondYes(): void
    {
        $headers = $this->createHeaders([
            'From' => 'user@example.com',
            'X-Autorespond' => 'yes',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects Precedence: bulk
     *
     * @return void
     */
    public function testIsAutoReplyDetectsPrecedenceBulk(): void
    {
        $headers = $this->createHeaders([
            'From' => 'notifications@example.com',
            'Precedence' => 'bulk',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects Precedence: list
     *
     * @return void
     */
    public function testIsAutoReplyDetectsPrecedenceList(): void
    {
        $headers = $this->createHeaders([
            'From' => 'mailinglist@example.com',
            'Precedence' => 'list',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects Precedence: junk
     *
     * @return void
     */
    public function testIsAutoReplyDetectsPrecedenceJunk(): void
    {
        $headers = $this->createHeaders([
            'From' => 'spam@example.com',
            'Precedence' => 'junk',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply returns false for normal emails
     *
     * @return void
     */
    public function testIsAutoReplyReturnsFalseForNormalEmails(): void
    {
        $headers = $this->createHeaders([
            'From' => 'user@example.com',
            'To' => 'support@example.com',
            'Subject' => 'Help with my order',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertFalse($result);
    }

    /**
     * Test isAutoReply is case-insensitive for header values
     *
     * @return void
     */
    public function testIsAutoReplyIsCaseInsensitive(): void
    {
        $headers = $this->createHeaders([
            'Auto-Submitted' => 'AUTO-REPLIED',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply detects values with additional text
     *
     * @return void
     */
    public function testIsAutoReplyDetectsValuesWithAdditionalText(): void
    {
        $headers = $this->createHeaders([
            'Auto-Submitted' => 'auto-replied; owner-email="admin@example.com"',
        ]);

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertTrue($result);
    }

    /**
     * Test isAutoReply with empty headers array
     *
     * @return void
     */
    public function testIsAutoReplyWithEmptyHeaders(): void
    {
        $headers = [];

        $result = $this->GmailService->isAutoReply($headers);
        $this->assertFalse($result);
    }
}
