<?php
declare(strict_types=1);

use Migrations\AbstractMigration;

/**
 * CreateComprasComments Migration
 *
 * Creates the compras_comments table for storing all purchase request comments.
 * Similar structure to ticket_comments with additional email tracking.
 *
 * @version 1.0.0 - Consolidated from 2 migrations (2026-01-05)
 */
class CreateComprasComments extends AbstractMigration
{
    /**
     * Create compras_comments table with complete schema
     *
     * @return void
     */
    public function change(): void
    {
        $table = $this->table('compras_comments', ['signed' => false]);

        $table
            // Relationships
            ->addColumn('compra_id', 'integer', [
                'null' => false,
                'signed' => false,
                'comment' => 'Reference to parent purchase request',
            ])
            ->addColumn('user_id', 'integer', [
                'null' => true,
                'signed' => false,
                'comment' => 'User who created the comment (null for system comments)',
            ])

            // Comment content
            ->addColumn('body', 'text', [
                'null' => false,
                'comment' => 'Comment text content (supports HTML)',
            ])

            // Comment classification
            ->addColumn('comment_type', 'string', [
                'limit' => 20,
                'default' => 'public',
                'null' => false,
                'comment' => 'public = visible to requester, internal = agent notes only',
            ])
            ->addColumn('is_system_comment', 'boolean', [
                'default' => false,
                'null' => false,
                'comment' => 'True if automatically generated by system',
            ])

            // Email tracking
            ->addColumn('email_to', 'text', [
                'null' => true,
                'comment' => 'JSON array of To recipients when sent as email',
            ])
            ->addColumn('email_cc', 'text', [
                'null' => true,
                'comment' => 'JSON array of CC recipients when sent as email',
            ])
            ->addColumn('sent_as_email', 'boolean', [
                'default' => false,
                'null' => false,
                'comment' => 'True if comment was sent as email notification',
            ])

            // Timestamps
            ->addColumn('created', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Comment creation timestamp',
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Last modification timestamp',
            ])

            // Indexes for performance
            ->addIndex(['compra_id'], [
                'name' => 'idx_compra_id',
            ])
            ->addIndex(['user_id'], [
                'name' => 'idx_user_id',
            ])
            ->addIndex(['comment_type'], [
                'name' => 'idx_comment_type',
            ])
            ->addIndex(['compra_id', 'created'], [
                'name' => 'idx_compra_created',
            ])

            // Foreign key constraints
            ->addForeignKey('compra_id', 'compras', 'id', [
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
                'constraint' => 'fk_compras_comments_compra',
            ])
            ->addForeignKey('user_id', 'users', 'id', [
                'delete' => 'SET_NULL',
                'update' => 'CASCADE',
                'constraint' => 'fk_compras_comments_user',
            ])

            ->create();
    }
}
