<?php
declare(strict_types=1);

use Migrations\AbstractMigration;

/**
 * CreatePqrsComments Migration
 *
 * Creates the pqrs_comments table for storing all PQRS comments.
 * Similar structure to ticket_comments with email tracking.
 *
 * @version 1.0.0 - Consolidated from 2 migrations (2026-01-05)
 */
class CreatePqrsComments extends AbstractMigration
{
    /**
     * Create pqrs_comments table with complete schema
     *
     * @return void
     */
    public function change(): void
    {
        $table = $this->table('pqrs_comments', ['signed' => false]);

        $table
            // Relationships
            ->addColumn('pqrs_id', 'integer', [
                'null' => false,
                'signed' => false,
                'comment' => 'Reference to parent PQRS',
            ])
            ->addColumn('user_id', 'integer', [
                'null' => false,
                'signed' => false,
                'comment' => 'User who created the comment (customer service agent)',
            ])

            // Comment content
            ->addColumn('body', 'text', [
                'null' => false,
                'comment' => 'Comment text content (supports HTML)',
            ])

            // Comment classification
            ->addColumn('comment_type', 'enum', [
                'values' => ['public', 'internal'],
                'default' => 'public',
                'null' => false,
                'comment' => 'public = visible to requester, internal = agent notes only',
            ])
            ->addColumn('is_system_comment', 'boolean', [
                'default' => false,
                'null' => false,
                'comment' => 'True if automatically generated by system',
            ])

            // Email tracking (when comment is sent as email reply)
            ->addColumn('email_to', 'text', [
                'null' => true,
                'comment' => 'JSON array of To recipients when sent as email',
            ])
            ->addColumn('email_cc', 'text', [
                'null' => true,
                'comment' => 'JSON array of CC recipients when sent as email',
            ])

            // Timestamps
            ->addColumn('created', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Comment creation timestamp',
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Last modification timestamp',
            ])

            // Indexes for performance
            ->addIndex(['pqrs_id'], [
                'name' => 'idx_pqrs_id',
            ])
            ->addIndex(['user_id'], [
                'name' => 'idx_user_id',
            ])
            ->addIndex(['created'], [
                'name' => 'idx_created',
            ])
            ->addIndex(['comment_type'], [
                'name' => 'idx_comment_type',
            ])
            ->addIndex(['pqrs_id', 'created'], [
                'name' => 'idx_pqrs_created',
            ])

            // Foreign key constraints
            ->addForeignKey('pqrs_id', 'pqrs', 'id', [
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
                'constraint' => 'fk_pqrs_comments_pqrs',
            ])
            ->addForeignKey('user_id', 'users', 'id', [
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
                'constraint' => 'fk_pqrs_comments_user',
            ])

            ->create();
    }
}
