<?php
declare(strict_types=1);

use Migrations\AbstractMigration;

/**
 * CreateTicketComments Migration
 *
 * Creates the ticket_comments table for storing all ticket comments including:
 * - Public comments (visible to requesters)
 * - Internal notes (visible only to agents)
 * - System-generated comments (automated status changes, etc.)
 * - Email recipient tracking for comments sent as email responses
 *
 * @version 1.0.0 - Consolidated from 2 migrations (2026-01-05)
 */
class CreateTicketComments extends AbstractMigration
{
    /**
     * Create ticket_comments table with complete schema
     *
     * @return void
     */
    public function change(): void
    {
        $table = $this->table('ticket_comments', ['signed' => false]);

        $table
            // Relationships
            ->addColumn('ticket_id', 'integer', [
                'null' => false,
                'signed' => false,
                'comment' => 'Reference to parent ticket',
            ])
            ->addColumn('user_id', 'integer', [
                'null' => false,
                'signed' => false,
                'comment' => 'User who created the comment (agent or system)',
            ])

            // Comment content
            ->addColumn('body', 'text', [
                'null' => false,
                'comment' => 'Comment text content (supports HTML)',
            ])

            // Comment classification
            ->addColumn('comment_type', 'enum', [
                'values' => ['public', 'internal'],
                'default' => 'public',
                'null' => false,
                'comment' => 'public = visible to requester, internal = agent notes only',
            ])
            ->addColumn('is_system_comment', 'boolean', [
                'default' => false,
                'null' => false,
                'comment' => 'True if automatically generated by system (status changes, etc.)',
            ])

            // Email tracking (when comment is sent as email reply)
            ->addColumn('email_to', 'text', [
                'null' => true,
                'comment' => 'JSON array of To recipients when sent as email response',
            ])
            ->addColumn('email_cc', 'text', [
                'null' => true,
                'comment' => 'JSON array of CC recipients when sent as email response',
            ])

            // Timestamps
            ->addColumn('created', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Comment creation timestamp',
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'null' => true,
                'comment' => 'Last modification timestamp',
            ])

            // Indexes for performance
            ->addIndex(['ticket_id'], [
                'name' => 'idx_ticket_id',
            ])
            ->addIndex(['user_id'], [
                'name' => 'idx_user_id',
            ])
            ->addIndex(['created'], [
                'name' => 'idx_created',
            ])
            ->addIndex(['comment_type'], [
                'name' => 'idx_comment_type',
            ])
            ->addIndex(['is_system_comment'], [
                'name' => 'idx_is_system_comment',
            ])

            // Composite indexes for common queries
            ->addIndex(['ticket_id', 'created'], [
                'name' => 'idx_ticket_created',
            ])
            ->addIndex(['ticket_id', 'comment_type'], [
                'name' => 'idx_ticket_comment_type',
            ])

            // Foreign key constraints
            ->addForeignKey('ticket_id', 'tickets', 'id', [
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
                'constraint' => 'fk_ticket_comments_ticket',
            ])
            ->addForeignKey('user_id', 'users', 'id', [
                'delete' => 'CASCADE',
                'update' => 'CASCADE',
                'constraint' => 'fk_ticket_comments_user',
            ])

            ->create();
    }
}
